package edu.tum.ase.springtestpyramid.it;

import edu.tum.ase.springtestpyramid.models.Project;
import edu.tum.ase.springtestpyramid.repositories.ProjectRepository;
import org.junit.After;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@DataJpaTest
public class ProjectRepositoryIT {
    @Autowired
    private ProjectRepository systemUnderTest;

    @After
    public void tearDown() throws Exception {
        // This can be used here as `deleteAll()` is generated by Spring Data
        systemUnderTest.deleteAll();
    }

    @Test
    public void should_ReturnPersistedProject_When_QueriedByExistingName() {
        // given

        // when

        // then
    }
}
