server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    eureka-server-port: 8761
    fetch-registry: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ["http://localhost:3000", "http://34.159.0.106:3000", "http://34.159.117.103:3000", "http://34.159.69.43:3000"]
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
            exposedHeaders: "Set-Cookie"
        add-to-simple-url-handler-mapping: true
  application:
    name: api-gateway-service

